name: Alibaba Cloud Registry Docker Image CI

# 手动执行流程
on: workflow_dispatch

jobs:
  push_to_acr:
    name: Push Docker image to Alibaba Cloud Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Alibaba Cloud Registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login --username="${{ secrets.ACR_USERNAME }}" --password-stdin ${{ secrets.ACR_REGISTRY }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v1
        with:
          images: ${{ secrets.ACR_REGISTRY }}/trueai-org/midjourney-proxy
          
      # 构建基础镜像（轻量版，支持Discord、悠船绘图）
      - name: Build and push Docker image to Alibaba Cloud Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/Midjourney.API/Dockerfile
          push: true
          tags: |
            ${{ secrets.ACR_REGISTRY }}/trueai-org/midjourney-proxy:${{ steps.meta.outputs.version }}-lite
            ${{ secrets.ACR_REGISTRY }}/trueai-org/midjourney-proxy:lite
          labels: ${{ steps.meta.outputs.labels }}
          
      # 构建官方镜像（完整版，支持Discord、悠船、官方绘图，包含更多依赖）
      - name: Build and push official Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/Midjourney.API/Dockerfile.official
          push: true
          tags: |
            ${{ secrets.ACR_REGISTRY }}/trueai-org/midjourney-proxy:${{ steps.meta.outputs.version }}
            ${{ secrets.ACR_REGISTRY }}/trueai-org/midjourney-proxy:latest
          labels: ${{ steps.meta.outputs.labels }}